@GW_HostAddress = http://localhost:5227

GET {{GW_HostAddress}}/protected/weatherforecast/
Accept: application/json
X-Client-Type: User

###
GET {{GW_HostAddress}}/product/weatherforecast/
Accept: application/json
X-Client-Type: User

###